#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [9]:
Array=np.zeros(10)
print (repr(Array))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


#### Create an array of 10 ones

In [13]:
Array_of_ones=np.ones(10)
print (repr(Array_of_ones))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


#### Create an array of 10 fives

In [21]:
Array_of_fives=np.full(10,5)
print (repr(Array_of_fives))

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


#### Create an array of the integers from 10 to 50

In [41]:
np.arange(10,51)
print (repr(Integers_Array))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])


#### Create an array of all the even integers from 10 to 50

In [47]:
Even=np.arange(10,51,2)
print (repr(Even))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])


#### Create a 3x3 matrix with values ranging from 0 to 8

In [61]:
matrix=np.arange(0,9).reshape(3,3)
print (repr(matrix))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


#### Create a 3x3 identity matrix

In [75]:
Identity=np.identity(3).reshape(3,3)
print (repr(Identity))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


#### Use NumPy to generate a random number between 0 and 1

In [100]:
Random=np.random.random()
print (repr(Random))

0.5423814177003334


 Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [116]:
Random_numbers=np.random.randn(25)
print (repr(Random_numbers))

array([ 0.23688183,  0.03091508,  0.86131635, -0.2219844 , -0.54190754,
        0.95503471,  0.74977716, -0.48872363,  0.84612332,  0.16097309,
       -0.35920582, -0.71559155, -1.22112758,  0.27165365,  0.29358399,
        0.16951213,  1.12062509,  0.26758451, -0.56970854,  0.73565842,
        0.77553825, -0.5729389 , -1.47239855,  0.07691211,  0.35122943])


#### Create the following matrix:

In [120]:
Matrix=np.arange(0.01, 1.01, 0.01).reshape(10,10)
print (repr(Matrix))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])


#### Create an array of 20 linearly spaced points between 0 and 1:

In [130]:
linearly_spaced=np.linspace(0,1,20)
print (repr(linearly_spaced))

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [2]:

import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
sub_matrix = mat[2:, 1:]
print (repr(sub_matrix))

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])


In [4]:
    Specific_value=mat[3,4]
    print (Specific_value)

20


20

In [17]:
Specific_matrix=mat[0:3, 1:2]
print(repr(Specific_matrix))

array([[ 2],
       [ 7],
       [12]])


array([[ 2],
       [ 7],
       [12]])

In [43]:
New_row=mat[4,0:]
print(repr(New_row))

array([21, 22, 23, 24, 25])


array([21, 22, 23, 24, 25])

In [47]:
Rows=mat[3:,0:]
print(repr(Rows))

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [49]:
Sum=np.sum(mat)
print (Sum)

325


#### Get the standard deviation of the values in mat

In [51]:
Standard_Deviation=np.std(mat)
print(Standard_Deviation)

7.211102550927978


# Great Job!